# --- Étape 1 : Construction ---
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration=production

# --- Étape 2 : Serveur Web Nginx ---
FROM nginx:alpine

# Copie de la configuration Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copie des fichiers statiques compilés d'Angular
COPY --from=builder /usr/src/app/dist/frontend/browser /usr/share/nginx/html

# Expose le port 80 pour le trafic HTTP public
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
